// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientSubscribeToRoom.proto

package com.iGap.proto;

public final class ProtoClientSubscribeToRoom {
  private ProtoClientSubscribeToRoom() {
  }

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClientSubscribeToRoomOrBuilder extends
          // @@protoc_insertion_point(interface_extends:proto.ClientSubscribeToRoom)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    boolean hasRequest();
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    com.iGap.proto.ProtoRequest.Request getRequest();
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    com.iGap.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder();

    /**
     * <code>optional uint64 room_id = 2;</code>
     */
    long getRoomId();
  }
  /**
   * Protobuf type {@code proto.ClientSubscribeToRoom}
   */
  public static final class ClientSubscribeToRoom extends com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:proto.ClientSubscribeToRoom)
          ClientSubscribeToRoomOrBuilder {
    // Use ClientSubscribeToRoom.newBuilder() to construct.
    private ClientSubscribeToRoom(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientSubscribeToRoom() {
      roomId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private ClientSubscribeToRoom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.iGap.proto.ProtoRequest.Request.Builder subBuilder = null;
              if (request_ != null) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(com.iGap.proto.ProtoRequest.Request.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              roomId_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.iGap.proto.ProtoClientSubscribeToRoom.internal_static_proto_ClientSubscribeToRoom_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
      return com.iGap.proto.ProtoClientSubscribeToRoom.internal_static_proto_ClientSubscribeToRoom_fieldAccessorTable.ensureFieldAccessorsInitialized(com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom.class, com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom.Builder.class);
    }

    public static final int REQUEST_FIELD_NUMBER = 1;
    private com.iGap.proto.ProtoRequest.Request request_;
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    public boolean hasRequest() {
      return request_ != null;
    }
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    public com.iGap.proto.ProtoRequest.Request getRequest() {
      return request_ == null ? com.iGap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
    }
    /**
     * <code>optional .proto.Request request = 1;</code>
     */
    public com.iGap.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
      return getRequest();
    }

    public static final int ROOM_ID_FIELD_NUMBER = 2;
    private long roomId_;
    /**
     * <code>optional uint64 room_id = 2;</code>
     */
    public long getRoomId() {
      return roomId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      if (request_ != null) {
        output.writeMessage(1, getRequest());
      }
      if (roomId_ != 0L) {
        output.writeUInt64(2, roomId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (request_ != null) {
        size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getRequest());
      }
      if (roomId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream.computeUInt64Size(2, roomId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom)) {
        return super.equals(obj);
      }
      com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom other = (com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom) obj;

      boolean result = true;
      result = result && (hasRequest() == other.hasRequest());
      if (hasRequest()) {
        result = result && getRequest().equals(other.getRequest());
      }
      result = result && (getRoomId() == other.getRoomId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasRequest()) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
      }
      hash = (37 * hash) + ROOM_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getRoomId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom parseFrom(java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
      return newBuilder();
    }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ClientSubscribeToRoom}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:proto.ClientSubscribeToRoom)
            com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.iGap.proto.ProtoClientSubscribeToRoom.internal_static_proto_ClientSubscribeToRoom_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return com.iGap.proto.ProtoClientSubscribeToRoom.internal_static_proto_ClientSubscribeToRoom_fieldAccessorTable.ensureFieldAccessorsInitialized(com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom.class, com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom.Builder.class);
      }

      // Construct using com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (requestBuilder_ == null) {
          request_ = null;
        } else {
          request_ = null;
          requestBuilder_ = null;
        }
        roomId_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return com.iGap.proto.ProtoClientSubscribeToRoom.internal_static_proto_ClientSubscribeToRoom_descriptor;
      }

      public com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom getDefaultInstanceForType() {
        return com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom.getDefaultInstance();
      }

      public com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom build() {
        com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom buildPartial() {
        com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom result = new com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom(this);
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        result.roomId_ = roomId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }

      public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
        return (Builder) super.setField(field, value);
      }

      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }

      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }

      public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }

      public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom) {
          return mergeFrom((com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom other) {
        if (other == com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.getRoomId() != 0L) {
          setRoomId(other.getRoomId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.iGap.proto.ProtoRequest.Request request_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<com.iGap.proto.ProtoRequest.Request, com.iGap.proto.ProtoRequest.Request.Builder, com.iGap.proto.ProtoRequest.RequestOrBuilder> requestBuilder_;
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public boolean hasRequest() {
        return requestBuilder_ != null || request_ != null;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public com.iGap.proto.ProtoRequest.Request getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? com.iGap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder setRequest(com.iGap.proto.ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder setRequest(com.iGap.proto.ProtoRequest.Request.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder mergeRequest(com.iGap.proto.ProtoRequest.Request value) {
        if (requestBuilder_ == null) {
          if (request_ != null) {
            request_ = com.iGap.proto.ProtoRequest.Request.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = null;
          onChanged();
        } else {
          request_ = null;
          requestBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public com.iGap.proto.ProtoRequest.Request.Builder getRequestBuilder() {

        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      public com.iGap.proto.ProtoRequest.RequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ? com.iGap.proto.ProtoRequest.Request.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>optional .proto.Request request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<com.iGap.proto.ProtoRequest.Request, com.iGap.proto.ProtoRequest.Request.Builder, com.iGap.proto.ProtoRequest.RequestOrBuilder> getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<com.iGap.proto.ProtoRequest.Request, com.iGap.proto.ProtoRequest.Request.Builder, com.iGap.proto.ProtoRequest.RequestOrBuilder>(getRequest(), getParentForChildren(), isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private long roomId_;
      /**
       * <code>optional uint64 room_id = 2;</code>
       */
      public long getRoomId() {
        return roomId_;
      }
      /**
       * <code>optional uint64 room_id = 2;</code>
       */
      public Builder setRoomId(long value) {

        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 room_id = 2;</code>
       */
      public Builder clearRoomId() {

        roomId_ = 0L;
        onChanged();
        return this;
      }

      public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.ClientSubscribeToRoom)
    }

    // @@protoc_insertion_point(class_scope:proto.ClientSubscribeToRoom)
    private static final com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom();
    }

    public static com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientSubscribeToRoom> PARSER = new com.google.protobuf.AbstractParser<ClientSubscribeToRoom>() {
      public ClientSubscribeToRoom parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientSubscribeToRoom(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientSubscribeToRoom> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientSubscribeToRoom> getParserForType() {
      return PARSER;
    }

    public com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoom getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ClientSubscribeToRoomResponseOrBuilder extends
          // @@protoc_insertion_point(interface_extends:proto.ClientSubscribeToRoomResponse)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    com.iGap.proto.ProtoResponse.Response getResponse();
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    com.iGap.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder();
  }
  /**
   * Protobuf type {@code proto.ClientSubscribeToRoomResponse}
   */
  public static final class ClientSubscribeToRoomResponse extends com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:proto.ClientSubscribeToRoomResponse)
          ClientSubscribeToRoomResponseOrBuilder {
    // Use ClientSubscribeToRoomResponse.newBuilder() to construct.
    private ClientSubscribeToRoomResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientSubscribeToRoomResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private ClientSubscribeToRoomResponse(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.iGap.proto.ProtoResponse.Response.Builder subBuilder = null;
              if (response_ != null) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(com.iGap.proto.ProtoResponse.Response.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.iGap.proto.ProtoClientSubscribeToRoom.internal_static_proto_ClientSubscribeToRoomResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
      return com.iGap.proto.ProtoClientSubscribeToRoom.internal_static_proto_ClientSubscribeToRoomResponse_fieldAccessorTable.ensureFieldAccessorsInitialized(com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse.class, com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse.Builder.class);
    }

    public static final int RESPONSE_FIELD_NUMBER = 1;
    private com.iGap.proto.ProtoResponse.Response response_;
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    public boolean hasResponse() {
      return response_ != null;
    }
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    public com.iGap.proto.ProtoResponse.Response getResponse() {
      return response_ == null ? com.iGap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
    }
    /**
     * <code>optional .proto.Response response = 1;</code>
     */
    public com.iGap.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
      return getResponse();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      if (response_ != null) {
        output.writeMessage(1, getResponse());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (response_ != null) {
        size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getResponse());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse)) {
        return super.equals(obj);
      }
      com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse other = (com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse) obj;

      boolean result = true;
      result = result && (hasResponse() == other.hasResponse());
      if (hasResponse()) {
        result = result && getResponse().equals(other.getResponse());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasResponse()) {
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse parseFrom(java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
      return newBuilder();
    }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ClientSubscribeToRoomResponse}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:proto.ClientSubscribeToRoomResponse)
            com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.iGap.proto.ProtoClientSubscribeToRoom.internal_static_proto_ClientSubscribeToRoomResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return com.iGap.proto.ProtoClientSubscribeToRoom.internal_static_proto_ClientSubscribeToRoomResponse_fieldAccessorTable.ensureFieldAccessorsInitialized(com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse.class, com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse.Builder.class);
      }

      // Construct using com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (responseBuilder_ == null) {
          response_ = null;
        } else {
          response_ = null;
          responseBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return com.iGap.proto.ProtoClientSubscribeToRoom.internal_static_proto_ClientSubscribeToRoomResponse_descriptor;
      }

      public com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse getDefaultInstanceForType() {
        return com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse.getDefaultInstance();
      }

      public com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse build() {
        com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse buildPartial() {
        com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse result = new com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse(this);
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }

      public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
        return (Builder) super.setField(field, value);
      }

      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }

      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }

      public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }

      public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse) {
          return mergeFrom((com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse other) {
        if (other == com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse.getDefaultInstance()) return this;
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.iGap.proto.ProtoResponse.Response response_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<com.iGap.proto.ProtoResponse.Response, com.iGap.proto.ProtoResponse.Response.Builder, com.iGap.proto.ProtoResponse.ResponseOrBuilder> responseBuilder_;
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public boolean hasResponse() {
        return responseBuilder_ != null || response_ != null;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public com.iGap.proto.ProtoResponse.Response getResponse() {
        if (responseBuilder_ == null) {
          return response_ == null ? com.iGap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder setResponse(com.iGap.proto.ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder setResponse(com.iGap.proto.ProtoResponse.Response.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder mergeResponse(com.iGap.proto.ProtoResponse.Response value) {
        if (responseBuilder_ == null) {
          if (response_ != null) {
            response_ = com.iGap.proto.ProtoResponse.Response.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = null;
          onChanged();
        } else {
          response_ = null;
          responseBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public com.iGap.proto.ProtoResponse.Response.Builder getResponseBuilder() {

        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      public com.iGap.proto.ProtoResponse.ResponseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_ == null ? com.iGap.proto.ProtoResponse.Response.getDefaultInstance() : response_;
        }
      }
      /**
       * <code>optional .proto.Response response = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<com.iGap.proto.ProtoResponse.Response, com.iGap.proto.ProtoResponse.Response.Builder, com.iGap.proto.ProtoResponse.ResponseOrBuilder> getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<com.iGap.proto.ProtoResponse.Response, com.iGap.proto.ProtoResponse.Response.Builder, com.iGap.proto.ProtoResponse.ResponseOrBuilder>(getResponse(), getParentForChildren(), isClean());
          response_ = null;
        }
        return responseBuilder_;
      }

      public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.ClientSubscribeToRoomResponse)
    }

    // @@protoc_insertion_point(class_scope:proto.ClientSubscribeToRoomResponse)
    private static final com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse();
    }

    public static com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientSubscribeToRoomResponse> PARSER = new com.google.protobuf.AbstractParser<ClientSubscribeToRoomResponse>() {
      public ClientSubscribeToRoomResponse parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientSubscribeToRoomResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientSubscribeToRoomResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientSubscribeToRoomResponse> getParserForType() {
      return PARSER;
    }

    public com.iGap.proto.ProtoClientSubscribeToRoom.ClientSubscribeToRoomResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor internal_static_proto_ClientSubscribeToRoom_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_proto_ClientSubscribeToRoom_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor internal_static_proto_ClientSubscribeToRoomResponse_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_proto_ClientSubscribeToRoomResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
  static {
    java.lang.String[] descriptorData = {
            "\n\033ClientSubscribeToRoom.proto\022\005proto\032\rRe" +
                    "quest.proto\032\016Response.proto\"I\n\025ClientSub" +
                    "scribeToRoom\022\037\n\007request\030\001 \001(\0132\016.proto.Re" +
                    "quest\022\017\n\007room_id\030\002 \001(\004\"B\n\035ClientSubscrib" +
                    "eToRoomResponse\022!\n\010response\030\001 \001(\0132\017.prot" +
                    "o.ResponseB,\n\016com.iGap.protoB\032ProtoClien" +
                    "tSubscribeToRoomb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
      public com.google.protobuf.ExtensionRegistry assignDescriptors(com.google.protobuf.Descriptors.FileDescriptor root) {
        descriptor = root;
        return null;
      }
    };
    com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[]{
            com.iGap.proto.ProtoRequest.getDescriptor(), com.iGap.proto.ProtoResponse.getDescriptor(),
    }, assigner);
    internal_static_proto_ClientSubscribeToRoom_descriptor = getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ClientSubscribeToRoom_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_proto_ClientSubscribeToRoom_descriptor, new java.lang.String[]{"Request", "RoomId",});
    internal_static_proto_ClientSubscribeToRoomResponse_descriptor = getDescriptor().getMessageTypes().get(1);
    internal_static_proto_ClientSubscribeToRoomResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ClientSubscribeToRoomResponse_descriptor,
        new java.lang.String[] { "Response", });
    com.iGap.proto.ProtoRequest.getDescriptor();
    com.iGap.proto.ProtoResponse.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
